const QUESTIONS = [
  {
    id: "q1",
    category: "civilizations",
    difficulty: "easy",
    text: "Quale civiltà ha il Council Hall?",
    options: ["English", "French", "Mongols", "Delhi"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q2",
    category: "civilizations",
    difficulty: "easy",
    text: "Quale civiltà può impacchettare gli edifici?",
    options: ["Abbasid", "Mongols", "French", "Ottomans"],
    correctIndex: 1,
    durationMs: 8000,
  },
  {
    id: "q3",
    category: "ages",
    difficulty: "easy",
    text: "In quale età si sblocca il Castle Age?",
    options: ["Età I", "Età II", "Età III", "Età IV"],
    correctIndex: 2,
    durationMs: 8000,
  },
  {
    id: "q4",
    category: "landmarks",
    difficulty: "easy",
    text: "Quale civiltà ha il White Tower?",
    options: ["English", "Byzantines", "French", "Japanese"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q5",
    category: "civilizations",
    difficulty: "easy",
    text: "Quale civiltà usa il sistema Dynasty?",
    options: ["Chinese", "English", "Malians", "Rus"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q6",
    category: "units",
    difficulty: "easy",
    text: "Quale civiltà ha i Longbowmen?",
    options: ["English", "French", "Ottomans", "Japanese"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q7",
    category: "buildings",
    difficulty: "easy",
    text: "Quale civiltà costruisce l'Ovoo?",
    options: ["Mongols", "Abbasid", "Delhi", "Ayyubids"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q8",
    category: "units",
    difficulty: "easy",
    text: "Quale civiltà ha il Royal Knight?",
    options: ["French", "English", "Byzantines", "HRE"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q9",
    category: "landmarks",
    difficulty: "medium",
    text: "Il Dome of the Faith appartiene a quale civiltà?",
    options: ["Abbasid Dynasty", "Delhi Sultanate", "Ottomans", "Ayyubids"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q10",
    category: "units",
    difficulty: "medium",
    text: "Quale di queste unità è un'unità da polvere da sparo?",
    options: ["Longbowman", "Crossbowman", "Handcannoneer", "Spearman"],
    correctIndex: 2,
    durationMs: 8000,
  },
  {
    id: "q11",
    category: "landmarks",
    difficulty: "medium",
    text: "Il Golden Gate appartiene a quale civiltà?",
    options: ["Rus", "Mongols", "Ottomans", "French"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q12",
    category: "buildings",
    difficulty: "medium",
    text: "Quale edificio serve per avanzare di età nella maggior parte delle civiltà?",
    options: ["House", "Landmark", "Market", "Blacksmith"],
    correctIndex: 1,
    durationMs: 8000,
  },
  {
    id: "q13",
    category: "units",
    difficulty: "medium",
    text: "Quale unità countera meglio la cavalleria pesante in genere?",
    options: ["Spearman", "Villager", "Scout", "Monk"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q14",
    category: "ages",
    difficulty: "easy",
    text: "Qual è la prima età del gioco?",
    options: ["Feudal Age", "Dark Age", "Castle Age", "Imperial Age"],
    correctIndex: 1,
    durationMs: 8000,
  },
  {
    id: "q15",
    category: "civilizations",
    difficulty: "medium",
    text: "Quale civiltà può costruire i Mulberry Groves?",
    options: ["Chinese", "Malians", "Japanese", "Rus"],
    correctIndex: 2,
    durationMs: 8000,
  },
  {
    id: "q16",
    category: "landmarks",
    difficulty: "medium",
    text: "Il Barbican of the Sun è un landmark di quale civiltà?",
    options: ["Chinese", "Japanese", "Byzantines", "Delhi Sultanate"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q17",
    category: "units",
    difficulty: "medium",
    text: "Quale civiltà ha il Camel Archer?",
    options: ["French", "Abbasid Dynasty", "Rus", "Ottomans"],
    correctIndex: 1,
    durationMs: 8000,
  },
  {
    id: "q18",
    category: "civilizations",
    difficulty: "medium",
    text: "Quale civiltà ha il Mehter?",
    options: ["Ottomans", "English", "Byzantines", "Malians"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q19",
    category: "units",
    difficulty: "easy",
    text: "Quale di queste è un'unità religiosa?",
    options: ["Monk", "Spearman", "Horseman", "Villager"],
    correctIndex: 0,
    durationMs: 8000,
  },
  {
    id: "q20",
    category: "buildings",
    difficulty: "medium",
    text: "Dove vengono ricercati molti upgrade economici?",
    options: ["Barracks", "Mill", "Stable", "Keep"],
    correctIndex: 1,
    durationMs: 8000,
  },
  {
    id: "q21",
    category: "landmarks",
    difficulty: "hard",
    text: "Quale landmark degli Abbasid Dynasty sostituisce il classico sistema a landmark multipli?",
    options: ["House of Wisdom", "Dome of the Faith", "Golden Gate", "Grand Winery"],
    correctIndex: 0,
    durationMs: 9000,
  },
  {
    id: "q22",
    category: "civilizations",
    difficulty: "hard",
    text: "Quale civiltà utilizza il sistema Vizier Points?",
    options: ["Ottomans", "Ayyubids", "Delhi Sultanate", "Malians"],
    correctIndex: 0,
    durationMs: 9000,
  },
  {
    id: "q23",
    category: "units",
    difficulty: "hard",
    text: "Quale unità unica dei Rus è particolarmente efficace contro unità a distanza e leggere?",
    options: ["Warrior Monk", "Streltsy", "Knight", "Horse Archer"],
    correctIndex: 1,
    durationMs: 9000,
  },
  {
    id: "q24",
    category: "landmarks",
    difficulty: "hard",
    text: "Il Grand Winery appartiene a quale civiltà?",
    options: ["Byzantines", "Japanese", "Malians", "HRE"],
    correctIndex: 0,
    durationMs: 9000,
  },
  {
    id: "q25",
    category: "civilizations",
    difficulty: "hard",
    text: "Quale civiltà ottiene un forte focus sulle cisterns e sui bonus di rete interna?",
    options: ["Byzantines", "French", "Rus", "Ottomans"],
    correctIndex: 0,
    durationMs: 9000,
  },
];

const QUESTION_CATEGORIES = [
  { id: "civilizations", label: "Civilizzazioni" },
  { id: "units", label: "Unità" },
  { id: "landmarks", label: "Landmark" },
  { id: "buildings", label: "Edifici" },
  { id: "ages", label: "Età" },
];

module.exports = { QUESTIONS, QUESTION_CATEGORIES };